global:
  scrape_interval:     15s

  external_labels:
    monitor: 'raft-monitor'

scrape_configs:
  - job_name: 'raft'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:59100', 'localhost:5901', 'localhost:5902', 'localhost:5903', 'localhost:5904', 'localhost:5905']
